# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    env:
      luceeVersion: 6.0.0.316-SNAPSHOT

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.GH_TOKEN}}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: lucee-script-runner-maven-cache

    - name: Cache Lucee files
      uses: actions/cache@v3
      with:
        path: _actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads-${{ env.luceeVersion }}
        restore-keys: |
          lucee-downloads

    - name: Build with Ant
      run: ant -noinput -verbose -buildfile build.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: hibernate-lex
        path: dist/*.lex

    - name: Checkout Lucee
      uses: actions/checkout@v3
      with:
        repository: lucee/lucee
        path: lucee

    - name: Run Lucee Test Suite (testLabels="orm")
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: light-${{ env.luceeVersion }}
        extensionDir: ${{ github.workspace }}/dist
      env:
        testLabels: orm
        testAdditional: ${{ github.workspace }}/tests

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ${{ github.workspace }}/lucee/test/reports/junit-test-results-${{env.luceeVersion}}.xml
        check_name: "Test Results"

  maven_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    strategy:
      fail-fast: false
      matrix:
        lucee_version: ["5.3.10.97"]
        java_version: [ "8", "11", "17" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{matrix.java_version}}'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode -f pom.xml -Dlucee.version=${{matrix.lucee_version}} -Djdk.version=${{matrix.java_version}} compile

  javadocs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-cache

      - name: Generate Javadocs
        run: mvn --batch-mode -f pom.xml javadoc:javadoc

      ## TODO: Publish apidocs to S3

      # - name: Commit Javadocs
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     file_pattern: "docs"
      #     commit_message: "📘 DOC: Rebuild API Javadocs __CI__"

  format:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-cache

      - name: Format Java source code
        run: mvn --batch-mode -f pom.xml formatter:format

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "docs"
          commit_message: "🤖 CI: Auto-format Java source __CI__"
